export const allowedRegions = [
  { code: 'SA', phoneCode: '966', name: 'السعودية' },
  { code: 'AE', phoneCode: '971', name: 'الإمارات' },
  { code: 'EG', phoneCode: '20', name: 'مصر' },
  { code: 'QA', phoneCode: '974', name: 'قطر' },
  { code: 'KW', phoneCode: '965', name: 'الكويت' },
  { code: 'BH', phoneCode: '973', name: 'البحرين' },
  { code: 'OM', phoneCode: '968', name: 'عمان' },
  { code: 'JO', phoneCode: '962', name: 'الأردن' },
  { code: 'LB', phoneCode: '961', name: 'لبنان' },
  { code: 'SY', phoneCode: '963', name: 'سوريا' },
  { code: 'IQ', phoneCode: '964', name: 'العراق' },
  { code: 'YE', phoneCode: '967', name: 'اليمن' },
  { code: 'MA', phoneCode: '212', name: 'المغرب' },
  { code: 'DZ', phoneCode: '213', name: 'الجزائر' },
  { code: 'TN', phoneCode: '216', name: 'تونس' },
  { code: 'LY', phoneCode: '218', name: 'ليبيا' },
  { code: 'SD', phoneCode: '249', name: 'السودان' },
  { code: 'PS', phoneCode: '970', name: 'فلسطين' },
];
